// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: menu/proto/menu.proto

package menu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message beer
type Beer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Beer) Reset() {
	*x = Beer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_menu_proto_menu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Beer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Beer) ProtoMessage() {}

func (x *Beer) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_menu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Beer.ProtoReflect.Descriptor instead.
func (*Beer) Descriptor() ([]byte, []int) {
	return file_menu_proto_menu_proto_rawDescGZIP(), []int{0}
}

func (x *Beer) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Beer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the beers
type ListBeersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Beers []*Beer `protobuf:"bytes,1,rep,name=beers,proto3" json:"beers,omitempty"`
}

func (x *ListBeersResponse) Reset() {
	*x = ListBeersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_menu_proto_menu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBeersResponse) ProtoMessage() {}

func (x *ListBeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_menu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBeersResponse.ProtoReflect.Descriptor instead.
func (*ListBeersResponse) Descriptor() ([]byte, []int) {
	return file_menu_proto_menu_proto_rawDescGZIP(), []int{1}
}

func (x *ListBeersResponse) GetBeers() []*Beer {
	if x != nil {
		return x.Beers
	}
	return nil
}

var File_menu_proto_menu_proto protoreflect.FileDescriptor

var file_menu_proto_menu_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x65, 0x6e, 0x75, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x6e,
	0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x65, 0x6e, 0x75, 0x1a, 0x1b, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x04, 0x42, 0x65,
	0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x35, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x65,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x62,
	0x65, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d, 0x65, 0x6e,
	0x75, 0x2e, 0x42, 0x65, 0x65, 0x72, 0x52, 0x05, 0x62, 0x65, 0x65, 0x72, 0x73, 0x32, 0x46, 0x0a,
	0x04, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x3e, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x65, 0x65,
	0x72, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x6d, 0x65, 0x6e,
	0x75, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x65, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x74, 0x72, 0x79, 0x2d, 0x67, 0x6f, 0x2d,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x6d, 0x65, 0x6e, 0x75, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_menu_proto_menu_proto_rawDescOnce sync.Once
	file_menu_proto_menu_proto_rawDescData = file_menu_proto_menu_proto_rawDesc
)

func file_menu_proto_menu_proto_rawDescGZIP() []byte {
	file_menu_proto_menu_proto_rawDescOnce.Do(func() {
		file_menu_proto_menu_proto_rawDescData = protoimpl.X.CompressGZIP(file_menu_proto_menu_proto_rawDescData)
	})
	return file_menu_proto_menu_proto_rawDescData
}

var file_menu_proto_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_menu_proto_menu_proto_goTypes = []interface{}{
	(*Beer)(nil),              // 0: menu.Beer
	(*ListBeersResponse)(nil), // 1: menu.ListBeersResponse
	(*emptypb.Empty)(nil),     // 2: google.protobuf.Empty
}
var file_menu_proto_menu_proto_depIdxs = []int32{
	0, // 0: menu.ListBeersResponse.beers:type_name -> menu.Beer
	2, // 1: menu.Menu.ListBeers:input_type -> google.protobuf.Empty
	1, // 2: menu.Menu.ListBeers:output_type -> menu.ListBeersResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_menu_proto_menu_proto_init() }
func file_menu_proto_menu_proto_init() {
	if File_menu_proto_menu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_menu_proto_menu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Beer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_menu_proto_menu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBeersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_menu_proto_menu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_menu_proto_menu_proto_goTypes,
		DependencyIndexes: file_menu_proto_menu_proto_depIdxs,
		MessageInfos:      file_menu_proto_menu_proto_msgTypes,
	}.Build()
	File_menu_proto_menu_proto = out.File
	file_menu_proto_menu_proto_rawDesc = nil
	file_menu_proto_menu_proto_goTypes = nil
	file_menu_proto_menu_proto_depIdxs = nil
}
